config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    resources :clothing_items, only: [:index, :create, :destroy, :edit, :update]
    resources :outfits
    resource :recommendations, only: [:new, :create]
  end

  resources :images, only: [:create, :destroy], defaults: {format: :json}

  root 'users#show'

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

end

app/models/outfit.rb
class Outfit < ApplicationRecord
  MAX_ROOM = 6
  belongs_to :user

  validates_presence_of :name

  has_many :outfit_clothing_items, dependent: :destroy
  has_many :clothing_items, through: :outfit_clothing_items

  accepts_nested_attributes_for :outfit_clothing_items, allow_destroy: true

  scope :most_recent_first, -> { order(created_at: :desc) }

  def remaining_room
    @remaining_room ||= MAX_ROOM - size
  end

  def price
    @price ||= clothing_items.pluck(:price).sum
  end

  def size
    @size ||= clothing_items.size
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user
  before_action :load_outfit, only: [:destroy, :edit, :update, :show]
  before_action :ensure_limit, only: [:new, :create]

  def index
    @outfits = @user.outfits.includes(clothing_items: [:image]).most_recent_first
    @clothes_number = @user.clothing_items.size
  end

  def show
    @clothing_items = @outfit.clothing_items.for_view.alphabetical
  end

  def new
    @outfit = Outfit.new
    @outfit.outfit_clothing_items.build
    @current_clothing_items = []
    @remaining_clothing_items = @user.clothing_items.for_view.most_recent_first
  end

  def create
    @outfit = @user.outfits.create(permitted_params)
    if @outfit.errors.any?
      redirect_back(fallback_location: new_user_outfit_path(@user))
    else
      redirect_to user_outfits_path(@user)
    end
  end

  def destroy
    @outfit.destroy
    @clothes_number = @user.clothing_items.size
  end

  def edit
    @current_clothing_items = @outfit.clothing_items.for_view.alphabetical
    @remaining_clothing_items = @user.clothing_items.for_view.most_recent_first.where.not(id: @current_clothing_items.pluck(:id))
  end

  def update
    if @outfit.update(permitted_params)
      redirect_to user_outfits_path(@user)
    else 
      redirect_back(fallback_location: edit_user_outfit_path(@user, @outfit))
    end
  end

  private

  def load_user
    @user = current_user
  end
  
  def load_outfit
    @outfit = @user.outfits.find(params[:id])
  end

  def ensure_limit
    redirect_back(fallback_location: user_outfits_path(@user)) if @user.outfits.size >= User::MAX_OUTFITS || @user.clothing_items.size < User::MIN_CLOTHES_FOR_OUTFIT
  end

  def permitted_params
    params.require(:outfit).permit(:name, outfit_clothing_items_attributes: [:id, :clothing_item_id, :_destroy])
  end

end

app/views/outfits/partials/_clothing_item_card.html.haml
.col-12{data: {id: clothing_item.id}}
  .card.clothing_item_card{data: {price: clothing_item.price }}
    .card-body
      .row
        .col-lg-6.image_side
          = image_tag clothing_item.image_url_or_default, alt: "Clothing image", class: "card-img-top"
        .col-lg-6.content-side
          %h4.card-title= clothing_item.name
          %h6.card-subtitle.mb-2.text-muted= number_to_currency(clothing_item.price)
          %strong= clothing_item.category.name
          %br
          %strong= clothing_item.brand.name
          %br
          %strong= clothing_item.color.name

app/views/outfits/partials/_form.html.haml
= form_with(model: [@user, @outfit], html: {class: "outfit_form"}) do |f|
  .row
    .col-8
      .card.existing_clothes
        .card-body.no_padding_right
          .row
            .col-6
              %h3.card-title Outfit Creator
              %h6.card-subtitle.mb-2.text-muted Drag and drop clothes from My Clothes to Outfit to add them.
              .form-group
                = f.label :name, "Name"
                = form_group_for f, :name do 
                  = f.text_field :name, required: true, class: "form-control"

              .row
                .col-6
                  %h4.card-title 
                    Total Cost: 
                    .total_cost= number_to_currency(@outfit.price)
                
                .col-6
                  %h4.card-title 
                    Remaining Room: 
                    .remaining_room= @outfit.remaining_room

              .outfit_clothing_items_fields
                = f.fields_for :outfit_clothing_items do |g|
                  = g.hidden_field :clothing_item_id, class: "clothing_item_id_field"
                  = g.check_box :_destroy, class: "destroy_item_#{g.object.clothing_item_id}"
                
              .card-footer.text-center
                = f.button "Save", data: {disable_with: disable_with_spinner('Saving') }, class: "btn btn-primary float-right"
                = link_to "Cancel", user_outfits_path(@user), class: "btn btn-default float-right"

            .col-6
              .row
                .card.outfit_clothes
                  .card-body
                    %h4.card-title Outfit Clothes
                    %h6.card-subtitle.mb-2.text-muted Add up to 6 clothing items
                    .row#left
                      = render partial: "outfits/partials/clothing_item_card", collection: @current_clothing_items, as: :clothing_item
                    
    
    .col-4
      .card.remaining_clothes
        .card-body
          %h4.card-title My Clothes
          .row#right
            = render partial: "outfits/partials/clothing_item_card", collection: @remaining_clothing_items, as: :clothing_item
        




:javascript
  window.initDragula();

app/views/outfits/partials/_outfit.html.haml
.col-lg-3.col-md-6.col-sm-6.col-xs-12{class: "outfit_card_#{outfit.id}"}
  .card.outfit_card
    .card-body
      %h4.card-title= outfit.name
      %h6.card-subtitle.mb-2.text-muted
        = number_to_currency(outfit.price)
        ●
        = "#{outfit.size} " + "item".pluralize(outfit.size)
      %h6.card-subtitle.mb-2.text-muted
      .clothing_item_images
        - outfit.clothing_items.each do |clothing_item|
          = image_tag clothing_item.image_url_or_default, alt: "Clothing image", class: "rounded-circle img-fluid"
    .card-footer.text-center
      = link_to "View", user_outfit_path(@user, outfit), remote: true, data: {disable_with: disable_with_spinner('Loading') } ,class: "btn btn-primary btn-sm float-right"
      = link_to "Delete", user_outfit_path(@user, outfit), method: :delete, remote: true, data: { disable_with: disable_with_spinner('Deleting'), confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm float-right"

app/views/outfits/partials/_outfit_modal_content.html.haml
.modal-header
  %h5#showOutfitLabel.modal-title= @outfit.name
  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
    %span{"aria-hidden" => "true"} ×
.modal-body
  %ul.nav.nav-pills.nav-pills-icons{:role => "tablist"}
    %li.nav-item
      = link_to "#card_view", role: "tab", data: {toggle: "tab"}, class: "nav-link active" do
        %i.material-icons dashboard
        Card View
    %li.nav-item
      = link_to "#table_view", role: "tab", data: {toggle: "tab"}, class: "nav-link" do
        %i.material-icons toc
        Table View
  .tab-content.tab-space
    #card_view.tab-pane.active
      .row
        - @clothing_items.each do |item|
          .col-lg-6.col-md-6.col-sm-6.col-xs-12.show_card_items
            = render "outfits/partials/clothing_item_card", clothing_item: item
    #table_view.tab-pane
      = render "outfits/partials/table"


.modal-footer
  %button.btn.btn-secondary.close_button{"data-dismiss" => "modal", :type => "button"} Close
  = link_to "Edit", edit_user_outfit_path(@user, @outfit), class: "btn btn-primary", data: { disable_with: disable_with_spinner('Loading') }

app/views/outfits/partials/_show_outfit.html.haml
%button.btn.btn-primary.show_outfit_modal_button{"data-target" => "#showOutfitModal", "data-toggle" => "modal", :type => "button"}
#showOutfitModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "showOutfitModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content

app/views/outfits/partials/_table.html.haml
.col-12
  %h5 Clothes
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th{:scope => "col"} Name
        %th{:scope => "col"} Brand
        %th{:scope => "col"} Category
        %th{:scope => "col"} Color
        %th{:scope => "col"} Price
    %tbody
      - @clothing_items.each do |item|
        %tr
          %th= item.name
          %td= item.brand.name
          %td= item.category.name
          %td= item.color.name
          %td= number_to_currency(item.price)
      %tr
        %td{:colspan => "4"} Total
        %td= number_to_currency(@outfit.price)