config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    resources :clothing_items, only: [:index, :create, :destroy, :edit, :update]
    resources :outfits
    resource :recommendations, only: [:new, :create]
  end

  resources :images, only: [:create, :destroy], defaults: {format: :json}

  root 'users#show'

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user

  def new
    @outfits_size = @user.outfits.size
    @clothing_items = @user.clothing_items
  end

  def create
    @recommendations = RecommendationsSearch.new({
      user_id: @user.id,
      clothing_item_id: params[:clothing_item_id]
    }).run
  end

  private

  def load_user
    @user = current_user
  end
  
end

app/views/recommendations/create.js.haml
var recommendations = $("#{escape_javascript(render(partial: "recommendations/partials/clothing_items"))}");
$('.recommendations_area .row').html(recommendations);
$(".spinner-border").hide();

app/views/recommendations/new.html.haml
- if @outfits_size > User::MIN_OUTFITS_FOR_RECOMMENDATION
  .col-12
    .card
      .card-body
        %h3.card-title Recommendations
        %h6.card-subtitle.mb-2.text-muted Select a Clothing Item to get matching Clothes Recommendations

        = form_with(url: user_recommendations_path(@user), method: :post, remote: true, class: "recommendations_form") do |f|
          = hidden_field_tag :clothing_item_id
              
          .container-fluid.card.clothing_options
            .row.flex-row.flex-nowrap.scrolling-wrapper
              - @clothing_items.each do |item|
                .col-lg-4.col-md-6.col-sm-6.col-xs-12
                  = render "outfits/partials/clothing_item_card", clothing_item: item

        .col-12.recommendations_area
          %h4 Matching Items 
          .row
          .d-flex.justify-content-center
            .spinner-border


- else
  .info
    .icon.icon-primary
      %i.material-icons remove_circle
    %h3.info-title Insufficient Outfits
    %p 
      = "Add at least #{User::MIN_OUTFITS_FOR_RECOMMENDATION}"
      = link_to "Outfit", user_outfits_path(@user)
      to enable Outfit Recommendation

:javascript
  window.outfitter.recommendations.selectClothingItem();