config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    resources :clothing_items, only: [:index, :create, :destroy, :edit, :update]
    resources :outfits
    resource :recommendations, only: [:new, :create]
  end

  resources :images, only: [:create, :destroy], defaults: {format: :json}

  root 'users#show'

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

end

app/models/clothing_item.rb
class ClothingItem < ApplicationRecord
  belongs_to :user
  belongs_to :brand
  belongs_to :category
  belongs_to :color
  belongs_to :image, optional: true, dependent: :destroy
  has_many :outfit_clothing_items, dependent: :destroy
  has_many :outfits, through: :outfit_clothing_items

  validates_presence_of :name, :price
  validates_uniqueness_of :name, scope: :user_id
  validates_numericality_of :price, greater_than_or_equal_to: 0

  scope :most_recent_first, -> { order(created_at: :desc) }
  scope :alphabetical, -> { order(name: :asc) }

  before_update :delete_old_image

  def self.for_view
    includes(:image, :brand, :color, :category)
  end

  def image_url_or_default
    image.present? ? image.file_name_url : 'no_image.jpg'
  end

  private

  def delete_old_image
    if image_id_was != image_id
      Image.find_by(id: image_id_was).try(:destroy)
    end
  end

end

app/controllers/clothing_items_controller.rb
class ClothingItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user 
  before_action :load_clothing_item, only: [:destroy, :edit, :update]

  def index
    @clothing_item = ClothingItem.new
    @clothing_items = @user.clothing_items.for_view.most_recent_first
  end

  def create
    @clothing_item = @user.clothing_items.create(permitted_params)
    if @clothing_item.errors.any?
      remove_image
    else
      @updated_clothing_item = @clothing_item
      @clothing_item = ClothingItem.new
    end
  end

  def destroy
    @clothing_item.destroy
  end

  def edit
  end

  def update
    @success = @clothing_item.update(permitted_params)
  end

  private

  def load_user
    @user = current_user
  end

  def load_clothing_item
    @clothing_item = @user.clothing_items.find(params[:id])
  end

  def permitted_params
    params.require(:clothing_item).permit(:name, :price, :brand_id, :category_id, :color_id, :image_id)
  end

  def remove_image
    @clothing_item.image.try(:destroy)
  end

end

app/views/clothing_items/partials/_card.html.haml
.card.cloting_item_card
  = image_tag clothing_item.image_url_or_default, alt: "Clothing image", class: "card-img-top"
  .card-body
    %h4.card-title= clothing_item.name
    %h6.card-subtitle.mb-2.text-muted= number_to_currency(clothing_item.price)
    %p.card-text
      %strong= clothing_item.category.name
    %p.card-text
      %strong= clothing_item.brand.name
    %p.card-text
      %strong= clothing_item.color.name
  .card-footer.text-center
    = link_to "Edit", edit_user_clothing_item_path(@user, clothing_item), remote: true, data: {disable_with: disable_with_spinner('Loading') } ,class: "btn btn-primary btn-sm float-right"
    = link_to "Delete", user_clothing_item_path(@user, clothing_item), method: :delete, remote: true, data: { disable_with: disable_with_spinner('Deleting'), confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm float-right"

app/views/clothing_items/partials/_clothing_item.html.haml
.col-lg-3.col-md-6.col-sm-6.col-xs-12{class: "clothing_item_card_#{clothing_item.id}"}
  = render partial: "clothing_items/partials/card", locals: {clothing_item: clothing_item}
  
      

app/views/clothing_items/partials/_edit_clothing_item.html.haml
%button.btn.btn-primary.edit_clothing_modal_button{"data-target" => "#editClothingItemModal", "data-toggle" => "modal", :type => "button"}
#editClothingItemModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "editClothingItemModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content

app/views/clothing_items/partials/_form.html.haml
= form_with(model: [@user, @clothing_item], remote: true) do |f|
  .modal-header
    %h5#createClothingItemLabel.modal-title New Clothing Item
    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
      %span{"aria-hidden" => "true"} ×
  .modal-body
    .form-group
      = f.label :name, "Name"
      = form_group_for f, :name do 
        = f.text_field :name, required: true, class: "form-control"
    .form-group
      = f.label :price, "Price"
      = form_group_for f, :price do 
        = f.number_field :price, required: true, min: 0, step: 0.01, class: "form-control"
    .row
      .col-4.form-group
        = f.label :brand_id, "Brand"
        = form_group_for f, :brand do 
          = f.select :brand_id, Brand.for_select, {}, {class: "form-control selectpicker", data: {style: "btn btn-link"}}
      .col-4.form-group
        = f.label :category_id, "Category"
        = form_group_for f, :category do 
          = f.select :category_id, Category.for_select, {}, {class: "form-control selectpicker", data: {style: "btn btn-link"}}
      .col-4.form-group
        = f.label :color_id, "Color"
        = form_group_for f, :color do
          = f.select :color_id, Color.for_select, {}, {class: "form-control selectpicker", data: {style: "btn btn-link"}}
    .form-group
      = f.label :image_id, "Image"
      = f.hidden_field :image_id, class: "form-control"
      #imageDropzone.dropzone

  .modal-footer
    %button.btn.btn-secondary.close_button{"data-dismiss" => "modal", :type => "button"} Close
    = f.button "Save", class: "btn btn-primary", data: { disable_with: disable_with_spinner('Saving') }

app/views/clothing_items/partials/_new_clothing_item.html.haml
#createClothingItemModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "createClothingItemLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      = render "clothing_items/partials/form"