config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    resources :clothing_items, only: [:index, :create, :destroy, :edit, :update]
    resources :outfits
    resource :recommendations, only: [:new, :create]
  end

  resources :images, only: [:create, :destroy], defaults: {format: :json}

  root 'users#show'

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def navbar_active_class(menu)
    controller = params[:controller]
    
    active = case menu
    when "home"
      controller == "users"
    when "clothes"
      controller == "clothing_items"
    when "outfits"
      controller == "outfits"
    when "recommendations"
      controller == "recommendations"
    else
      false
    end

    active ? "active" : ""
  end
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.bg-primary
  .container
    = link_to 'Outfitter', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.navbar-toggler-icon
      %span.navbar-toggler-icon
      %span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      %ul.navbar-nav
        %li.nav-item{class: navbar_active_class("home")}
          = link_to root_path, class: 'nav-link' do 
            Home
        %li.nav-item{class: navbar_active_class("outfits")}
          = link_to 'Outfits', user_outfits_path(current_user), class: 'nav-link'
        %li.nav-item{class: navbar_active_class("clothes")}
          = link_to 'Clothes', user_clothing_items_path(current_user), class: 'nav-link'
        %li.nav-item{class: navbar_active_class("recommendations")}
          = link_to 'Recommendations', new_user_recommendations_path(current_user), class: 'nav-link'

        %li.nav-item.dropdown.account-collapse
          .nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "javascript:;"}
            Account
          .dropdown-menu{"aria-labelledby" => "navbarDropdownMenuLink"}
            = link_to 'Settings', edit_user_registration_path(current_user), class: 'dropdown-item'
            = link_to 'Sign Out', signout_path, data: { turbolinks: false }, class: 'dropdown-item'
      
      .form-inline.ml-auto
        .nav-item.dropdown.account-area
          .dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "javascript:;"}
            Account
          .dropdown-menu{"aria-labelledby" => "navbarDropdownMenuLink"}
            = link_to 'Settings', edit_user_registration_path(current_user), class: 'dropdown-item'
            = link_to 'Sign Out', signout_path, data: { turbolinks: false }, class: 'dropdown-item'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Outfitter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body{class: "#{params[:controller].gsub("/", "-")}"}
    - if current_user.present?
      = render "layouts/navbar"
    = yield